ignore:
  - "deps/**/*"
coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 70
        threshold: 2%
        paths:
          - "src"
    patch:
      default:
        target: 70
        threshold: 2%
        paths:
          - "src"
