name: Node.js CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:

    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node: [22.x]

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - run: npm run build -if-present
    - name: Run headless test
      run: npm test

  codecov:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - run: npm ci
    - run: npm run build -if-present
    - run: npm run c8
    - run: npm run lcov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
