name: Node.js CI

on:
  push:
    branches: [ '*' ]

jobs:
  test:

    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm install --ignore-scripts
    - run: npx tsc
    - run: while npx mocha -g stress; do true; done

