name: Test npm package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to test'
        required: true

jobs:
  integration:

    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node: [21.x]

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      env:
        SQLITE_INSTALL_CMD: npm install sqlite-wasm-http@${{ github.event.inputs.version }}
      with:
        run: npm test
